name: Build

on: [push]

jobs:
  build:

    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    
    strategy:
      matrix:
        node-version: [10.x, 12.x]
        dotnet-version: [3.1.101]

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}             

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}  

    - name: restore packages
      run: |
        yarn install --frozen-lockfile
        dotnet restore
    - name: test
      run: yarn test
