name: Build

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [12,14]
        dotnet-version: [3.1.x]

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}             

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}  

    - name: restore packages
      run: |
        yarn install --frozen-lockfile
        dotnet restore

    - name: test
      run: yarn test
